use_frameworks!

platform :ios, '8.0'

target 'PoporDomainConfig_Example' do
  # 忽略pod第三方库文件警告
  inhibit_all_warnings!
  
  pod 'PoporDomainConfig', :path => '../'

  pod 'PoporFoundation/NSArray'
  
  target 'PoporDomainConfig_Tests' do
    inherit! :search_paths

    
  end
end
