use_frameworks!

platform :ios, '8.0'

# 推荐继续使用 传统的 pod
#source 'https://github.com/CocoaPods/Specs.git'
#source 'https://cdn.cocoapods.org/'

target 'PoporDomainConfig_Example' do
  
  # 忽略pod第三方库文件警告
  inhibit_all_warnings!
  
  pod 'PoporDomainConfig', :path => '../'
  
  #pod 'PoporFoundation', '1.21'
  pod 'PoporFoundation/NSArray'
  #pod 'PoporUI', '1.20'
  
  target 'PoporDomainConfig_Tests' do
    inherit! :search_paths
    
    
  end
end
